baseURL = 'https://hugotut.netlify.app/'
languageCode = 'en-us'
title = "Avinash's Portfolio"
theme="basic"

[params]
  author = "Avinash Murmu"
  description = "This is my portfolio website"
  gh_url = "https://api.github.com/users"
  gh_user = "avionics18"